### ISSUE TITLE
move the code for native into a separate file

### ISSUE THREAD

**Issue by thisconnect** [derhuerst/location#6]
hi

this looks very interesting, does this lib always use google https://github.com/watson/geocode-wifi/blob/master/index.js
or is that just a fallback?

if yes:
- could the fallback be disabled or
- could the db be hosted i.e. on ipfs?

**Comment by derhuerst** [comment]
[Whenever there native location server is available & works, it will use that. As a fallback, it will use `wifi-triangulate`, which talks to Google.](https://github.com/derhuerst/location/blob/5cdcf123ea56f4c0029129ec8400ede533553f2a/index.js#L64-L67)

> could the fallback be disabled [...]?

yes. an elegant way might be to move the native-only code into `native.js`, so that people can `require` `@derhuerst/location/native`.

> could the db be hosted i.e. on ipfs?

i guess. you're happy to do so. but this is clearly out of scope of this library.

**Comment by derhuerst** [comment]
note that the native location services might also [phone home](https://en.wikipedia.org/wiki/Phoning_home).

**Comment by thisconnect** [comment]
@derhuerst thanks!

**Comment by derhuerst** [comment]
I'll reopen this until this feature is actually implemented.
